-- MySQL Script generated by MySQL Workbench
-- Wed Oct  8 10:49:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria4142m
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria4142m
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria4142m` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria4142m` ;

-- -----------------------------------------------------
-- Table `concessionaria4142m`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria4142m`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria4142m`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria4142m`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(45) NOT NULL,
  `placa_modelo` VARCHAR(45) NULL,
  `cor_modelo` VARCHAR(20) NULL,
  `ano_modelo` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_modelo`, `marca_id_marca`),
  INDEX `fk_modelo_marca_idx` (`marca_id_marca` ASC) ,
  CONSTRAINT `fk_modelo_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `concessionaria4142m`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria4142m`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria4142m`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NOT NULL,
  `email_cliente` VARCHAR(100) NULL,
  `dt_nasc_cliente` DATE NULL,
  `fone_cliente` VARCHAR(20) NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria4142m`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria4142m`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `cpf_funcionario` CHAR(11) NOT NULL,
  `email_funcionario` VARCHAR(100) NULL,
  `fone_funcionario` VARCHAR(20) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria4142m`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria4142m`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` VARCHAR(45) NOT NULL,
  `valor_venda` DECIMAL(10,2) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_venda`, `cliente_id_cliente`, `modelo_id_modelo`, `funcionario_id_funcionario`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC) ,
  INDEX `fk_venda_modelo1_idx` (`modelo_id_modelo` ASC) ,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario` ASC) ,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `concessionaria4142m`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `concessionaria4142m`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `concessionaria4142m`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
